// File generated by FlutterFire CLI.
// Should be replaced with actual configuration from Firebase Console
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these placeholder values with your actual Firebase configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIDtAKIfYY5UdXiQ1vpYB1CTgT8HZhJ20',
    appId: '1:877846903380:web:7e878365db342d5133cbc1',
    messagingSenderId: '877846903380',
    projectId: 'fundracer-app',
    authDomain: 'fundracer-app.firebaseapp.com',
    storageBucket: 'fundracer-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDtAKIfYY5UdXiQ1vpYB1CTgT8HZhJ20',
    appId: '1:877846903380:android:034cf6c78075278b33cbc1',
    messagingSenderId: '877846903380',
    projectId: 'fundracer-app',
    storageBucket: 'fundracer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIDtAKIfYY5UdXiQ1vpYB1CTgT8HZhJ20',
    appId: '1:877846903380:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '877846903380',
    projectId: 'fundracer-app',
    storageBucket: 'fundracer-app.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.fundracer_app',
  );
} 